name: Deploy Workflows

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  relay-deploy:
    name: Relay Server Deployment
    if: contains(github.event.head_commit.message, 'relaydeploy') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Server to firese-server branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./firese-server
          publish_branch: firese-server
          force_orphan: true

  web-deploy:
    name: Web App Deployment
    if: contains(github.event.head_commit.message, 'deploy') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Dist to deployweb branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./firese-web/dist
          publish_branch: deployweb
          force_orphan: true
